### ISSUE TITLE
Not working after June 2018 release?

### ISSUE THREAD

**Issue by SindreKjetsa** [AnalyticsEarth/MasterScript#4]
This have been working great for the last releases, but today we upgraded to June 2018, as it came out yesterday. Now the extension is displaying: "The visualization was not found on the server: MasterScript". There was a few other extensions that had this error, but it was fixed by re-adding the extension. That did not work for MasterScript.

**Qlik:**
_"With the June 2018 Qlik Sense Enterprise release, Qlik will introduce updates which streamline the Qlik Sense client packaging through the introduction of Webpack, a new technology for module bundling JavaScript® applications. The introduction of Webpack technology will impact a subset of extensions and mashups that make use of unsupported internal Qlik Sense libraries or “private libraries” as described below.  Any solution, i.e. mashups or extensions that make use of a “private” Qlik Sense library should continue to function, but as with all upgrades, testing of your solutions is strongly recommended.  To address the need for use of these unsupported private libraries, Qlik will explore additional public APIs in forthcoming releases.   See the attached FAQ for further information."_

Is MasterScript using any “private libraries”, that could cause this?

**Comment by AnalyticsEarth** [comment]
Hi, I am aware of this issue and a fix is pending. The error is not directly related to the above but a fix should be in place within the next 24 hours.

**Comment by AnalyticsEarth** [comment]
Version 1.1.2 has just released to fix this issue.

**Comment by SindreKjetsa** [comment]
Awesome! Thanks alot, that was fast :+1:
