### ISSUE TITLE
{Enhancement} Add conditional column show expression

### ISSUE THREAD

**Issue by gmen85** [AnalyticsEarth/MasterScript#5]
Hello again AE, I have to say again a huge thanks for your extension.

Do you think it's possible to add a field for the new June 2018 feature "conditional show column when expression"? I am sure it will be much appreciated not only by me but by others too, as this feature, or rather the lack thereof, was a massive disappointment and rant from a multitude of Qlik customers, and it is great to have it back again.

**Comment by AnalyticsEarth** [comment]
Thanks for the feedback, and glad you using the extension.

Unfortunately these settings are not part of the master item, but set on the dimension for the chart, so it is not possible to set this in the library as part of the import. This has to be created on each table where the item is used and may not be the same for each instance of the column.
