### ISSUE TITLE
MasterScript no longer working (June 2018 Patch 1)

### ISSUE THREAD

**Issue by PaoloVallesi** [AnalyticsEarth/MasterScript#6]
On June 2018 Patch 1 the extension no longer work. 
You are using the 'autogenerated/qix/engine-api' which is probably no longer available since June 2018 therefore, requirejs fail to retrieve the js file (404). 
As qlik stated they introduced webpack and removed many of the private/undocumented library.
The console error:

`Failed to load resource: the server responded with a status of 404 (Not Found) /resources/autogenerated/qix/engine-api.js:1`

`Error: Script error for "autogenerated/qix/engine-api", needed by: extensions/MasterScript/MasterScript
http://requirejs.org/docs/errors.html#scripterror
    at makeError (client.c2fc1f6d5055907acb21.js:80)
    at HTMLScriptElement.onScriptError (client.c2fc1f6d5055907acb21.js:80)`

**Comment by AnalyticsEarth** [comment]
Please confirm you using v1.1.2 as this was fixed in June.

You may also need to clear the browser cache when you upgrade.

**Comment by PaoloVallesi** [comment]
damn cache! 
you were right! thanks!

keep up the great work!
